<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "crt_metatags"
 *
 * Auto generated by Extension Builder 2014-12-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cretection: Metatags',
	'description' => 'Organisiert die TYPO3 Metatags inklusive Dublin Core und bald OpenGraph-Informationen',
	'category' => 'plugin',
	'author' => 'Jonathan Starck',
	'author_email' => 'support@cretection.eu',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);